name: Deploy to prod appset

on:
  workflow_dispatch:
    inputs:
      build_version:
        description : 'Build Version'
        required: true
      deployments:
        description: 'Deployment names separated by (,)'
      all_deployments:
        type: boolean
      some_deployments:
        type: boolean


jobs:
  getting_app_name:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.app_names.outputs.app_name }}
    steps:
      - uses: actions/checkout@v3
      - name: deployments_name
        id: list_creation
        run: |
          declare -a app_names=()
          if ${{ github.event.inputs.all_deployments }} == true; then
            file_content=$(cat ".github/workflows/another/deployment-list.txt")
            for line in $file_content; do
              app_names+=("$line")
            done
          fi
          
          if ${{ github.event.inputs.some_deployments }} == true; then
            file_content=$(cat ".github/workflows/another/deployment-list.txt")
            for line in $file_content; do
              app_names+=("$line")
            done
          fi
          
          if [[ ! -z "${{ github.event.inputs.deployments }}" ]]; then
            IFS=',' read -ra additional_deployments <<< "${{ github.event.inputs.deployments }}"
            for i in "${!additional_deployments[@]}"; do
              additional_deployments[i]="${additional_deployments[i]#"${additional_deployments[i]%%[![:space:]]*}"}"
              additional_deployments[i]="${additional_deployments[i]%"${additional_deployments[i]##*[![:space:]]}"}"
            done
            app_names+=( "${additional_deployments[@]}" )
          fi
          
          declare -A unique_app_names
          for app in "${app_names[@]}"; do
            unique_app_names[$app]=1
          done
          app_names=("${!unique_app_names[@]}")
          
          echo "deployments_names=${app_names[*]}" >> $GITHUB_OUTPUT

      - name: app-name creation
        id: app_names
        run: |
          app_name=""
          app_list=(${{steps.list_creation.outputs.deployments_names}})
          for app in "${app_list[@]}"; do
            if [[ ${app_name} == "" ]]; then
              app_name="${app}"
            else
              app_name="${app_name},${app}"
            fi
          done
          echo "output: ${app_name}"
          echo "app_name=${app_name}" >> $GITHUB_OUTPUT
